### ISSUE TITLE
Is support frame_period=10ms?

### ISSUE THREAD

**Issue by lbqin** [mmorise/World#106]
I tried to experiment with frame_period=10ms and found that the synthesis effect was poor. Does the World support frame_period=10ms?

**Comment by mmorise** [comment]
Yes. WORLD vocoder supports the frame period of 10 ms. Generally, the speech synthesized with a 5-ms frame period is inferior to that of a 10-ms frame period in the sound quality. If the sound quality difference is clear, the program may have a bug in setting the frame period.

**Comment by lbqin** [comment]
Ok，thanks your reply！
