### ISSUE TITLE
Get bad wav after analysis and synthesis back

### ISSUE THREAD

**Issue by Yablon** [mmorise/World#107]
I get bad wav after the following operations:

```
./build/analysis test.wav test.f0 test.sp test.ap
./build/synthesis test.f0 test.sp test.ap debug.wav
```

Do you have any idea on how to fix this ?

The original test wav and debug wav are as follows
[wav.zip](https://github.com/mmorise/World/files/5391130/wav.zip)

Thank you !

**Comment by mmorise** [comment]
F0 estimation error is the main cause of degradation. The sound quality would improve by using Harvest() instead of Dio(). Harvest() generally provides a more reliable F0 compared with Dio().

**Comment by Yablon** [comment]
@mmorise Thank you for your kind reply. How about f0 estimated by REAPER or Praat ? Is that as reliable as Harvest() ?

**Comment by mmorise** [comment]
REAPER and Praat would work well when the noise in speech is small. The sound quality of synthesized speech generally depends on the voiced/unvoiced estimation in the F0 estimation process. To obtain good sound quality, Harvest is designed to reduce the error that the voiced section is wrongly identified as the unvoiced section.

**Comment by Yablon** [comment]
@mmorise Thank you !
