### ISSUE TITLE
Is it possible to publish a formal release version?

### ISSUE THREAD

**Issue by chxianying** [mmorise/World#110]
I noticed that the last release version in matlab is v0.2.4, and the code in GitHub has no specific version number. The project's main page also shows no releases published.  Is it possible to publish a formal(stable) release  version? This will make it easier for users to use stable versions and track changes in different versions. Thanks a lot!

**Comment by mmorise** [comment]
Thank you for your comment.

It is possible to make a formal release version based on the current source code. However, I'm too busy to do this work for a while. I will make time for the work in the next week or two. I will also check the source code to make the formal release.

**Comment by mmorise** [comment]
I released the formal release version. The version number is v1.0.0, but it is the same as the MATLAB version v0.2.4. I modified the source code's comment because my e-mail address is changed. On the other hand, I didn't change the source code in the algorithm.

**Comment by chxianying** [comment]
Thank you very much for providing the release version during your busy schedule. Also great thanks to you for providing this excellent text-to-speech tool.
