### ISSUE TITLE
some artifacts

### ISSUE THREAD

**Issue by HeYingnan** [mmorise/World#111]
when i use the WORLD analysis/synthesis my audio. It introduces some artifacts. if you can help me to find the reason?

**Comment by HeYingnan** [comment]
If you have time, I can send the audio to you.

**Comment by mmorise** [comment]
Thank you for your contact.

If possible, please give me the audio files (original and re-synthesized speech).
I will check the reason why the vocoder generated the artifacts.

**Comment by HeYingnan** [comment]
> Thank you for your contact.
> 
> If possible, please give me the audio files (original and re-synthesized speech).
> I will check the reason why the vocoder generated the artifacts.

can you give me a e-mail? I want to send you directly.

**Comment by HeYingnan** [comment]
you can send your email to 824655412@qq.com.

**Comment by mmorise** [comment]
My email address is mmorise@meiji.ac.jp.

**Comment by HeYingnan** [comment]
I sent you.

**Comment by HeYingnan** [comment]
> My email address is [mmorise@meiji.ac.jp](mailto:mmorise@meiji.ac.jp).

I sent you.
