### ISSUE TITLE
Synthesis real time test

### ISSUE THREAD

**Issue by zhangzhy52** [mmorise/World#119]
Hi,

I believe synth2 function (which is synth realtime) should be faster enough than the normal synth.

so I did the following test:
![截屏2021-06-04 下午3 16 34](https://user-images.githubusercontent.com/22312511/120761513-dad9f880-c547-11eb-9760-828576dde0aa.png)

When I increased the buffer size to 256, the result is:
![截屏2021-06-04 下午3 20 39](https://user-images.githubusercontent.com/22312511/120762043-6c496a80-c548-11eb-81fb-280ca6cbce6c.png)

After increasing buffer size to 2048:
![image](https://user-images.githubusercontent.com/22312511/120761169-7c147f00-c547-11eb-8c83-cf53ee869366.png)

It seems the Synthesis 2 takes almost the same time as synthesis 1. And the ring buffer synthesis is a little faster, but not significantly.

Is it a reasonable result? If it is, why Synth2 can be used in real time synth application?

Thank you!

**Comment by mmorise** [comment]
> Is it a reasonable result? If it is, why Synth2 can be used in real time synth application?
Yes, the computational cost of real-time synthesis is almost the same as synthesis 1 (offline synthesis).
The dominant factor related to the computational cost is the number of FFTs. The number of FFTs is the same in both the real-time and offline synthesis functions.

**Comment by zhangzhy52** [comment]
Thanks!
