### ISSUE TITLE
Encoding the spectral envelope and aperiodicity

### ISSUE THREAD

**Issue by utkrssh** [mmorise/World#122]
Hi,
I am making a diphone based TTS using WORLD vocoder. There seem to be two ways for storing the diphones.

One is to store them using a low-bit codec like opus. During synthesis, I can decode the required diphones, then analyse using WORLD, concatenate and finally synthesize. But the analysis seems to take a lot of CPU.

Second way is to store the analysed spectral envelope and aperiodicity. But it takes a lot of space even with the codec provided with the WORLD. Is there a better existing codec for encoding spectral envelope and aperiodicity?

**Comment by mmorise** [comment]
Thank you for your question.

I provided the codec to compress the spectral envelope and aperiodicity efficiently. Using this, you can obtain the spectral envelope and aperiodicity of 60 dimensions/frame and 5 dimensions/frame. We can also reduce the quantization bit used for them. These values have been determined to maintain the sound quality of the full-band speech compared with the parameters without codec. Frameshift affects the memory space, and the default value is 5 ms. 

It may be possible to improve the coding performance with another idea, but I currently have no idea.

**Comment by utkrssh** [comment]
Ok, so this brings to the question of how to quantize? As I need to prepare a diphone database, it would be best to train the quantization parameters on that database only. Should I use K-means? And what distance function should I use for spectral envelope and aperiodicity?

**Comment by mmorise** [comment]
https://ieeexplore.ieee.org/document/9023279
If you can access the above manuscript, you would obtain how to carry out the efficient quantization. Since it is difficult to explain the detailed information by only the text, please see the manuscript.

**Comment by utkrssh** [comment]
Thanks, I read the mentioned paper. I was wondering if [vector quantization](https://en.wikipedia.org/wiki/Vector_quantization) will be more helpful in my case because I have to encode data for a single speaker, so maybe I can make a codebook adapted to the speaker's voice.
