### ISSUE TITLE
Different between WORLD fft and SPTK fftr?

### ISSUE THREAD

**Issue by OnceJune** [mmorise/World#133]
Hi I tried to compare fft real forward functions between WORLD and SPTK and found they give different result. In my understanding the should do the samething, is there any different between these to libraries?

**Comment by mmorise** [comment]
Sorry, I didn't use SPTK's FFT function and used Ooura's FFT library in WORLD. I  have implemented a simple wrapper to give compatibility with FFTW. So I don't know the difference between them. On the other hand, I have checked that result is not different between FFTW and Ooura's FFT functions.

**Comment by OnceJune** [comment]
> Sorry, I didn't use SPTK's FFT function and used Ooura's FFT library in WORLD. I have implemented a simple wrapper to give compatibility with FFTW. So I don't know the difference between them. On the other hand, I have checked that result is not different between FFTW and Ooura's FFT functions.

Many thanks.
