### ISSUE TITLE
a bug in synthesisrealtime.cpp

### ISSUE THREAD

**Issue by xiaozhuo12138** [mmorise/World#138]
tmp = GetNextPulseLocationIndex(synth);
noise_size = tmp - current_location;

if function GetNextPulseLocationIndex return 0，noise_size  will be less than 0

**Comment by mmorise** [comment]
In cases where the function GetNextPulseLocationIndex() returns 0, the function CheckSynthesizer() used in the line 575 should also return 0. In this case, since the function Synthesis2() is terminated, we don't call the function GetNextPulseLocationIndex().

**Comment by xiaozhuo12138** [comment]
@mmorise thanks

**Comment by mmorise** [comment]
My memory of when I implemented it is a little fuzzy, but it seems that this process would be unnecessary. On the other hand, removing this process may introduce a bug because I don't check that it is reasonable.

**Comment by xiaozhuo12138** [comment]
@mmorise thanks
