### ISSUE TITLE
Proper ways to do feature conversion when working with HTS

### ISSUE THREAD

**Issue by bryandeng** [mmorise/World#14]
Hi Mr. Morise,

I'm replacing STRAIGHT with World in my HTS-based TTS system.

I only modified the `fs` parameter in `examples/synthesis.cpp` and followed the practice of Merlin to do feature extraction and conversion (`f0`, `sp`, `ap` <-> `lf0`, `mgc`, `bap`):
https://github.com/CSTR-Edinburgh/merlin/tree/master/misc/scripts/vocoder/world_v2

The synthesized audios sound great except for a few clippings. And I'm observing different clippings when switching between C++ and MATLAB versions of World (using the same `f0`, `sp` and `ap` files). 

- C++ analysis & synthesis
   ![phrase01_waveform_cpp_version](https://cloud.githubusercontent.com/assets/1997800/20662971/b979f792-b590-11e6-867a-0ad242ac5afc.jpg)
- C++ analysis & MATLAB synthesis
   ![phrase01_waveform_matlab_version](https://cloud.githubusercontent.com/assets/1997800/20662970/b979efd6-b590-11e6-9017-fbc7109d65dd.jpg)

I then trimmed out too large abnormal values in `bap`, which eliminated clippings when synthesized with the MATLAB version. But it didn't work for the C++ version.

So could you offer some suggestions on how to do feature conversion? Is any post-processing required beyond Merlin's practice?

**Comment by mmorise** [comment]
I think the aperiodicity estimator cannot work as expected.
Aperiodicity in WORLD must be in the range (0.0 < ap < 1.0).
Perhaps, there may be no safeguard.
If possible, could you give me the file of waveform?
I will check the source code with the file.

**Comment by bryandeng** [comment]
I think WORLD probably works correctly in this situation.

Since `ap` for synthesis is generated by HTS and SPTK, it's not guaranteed to be in the range
(as there might be numerical instabilities in the toolkits, even though the training data is between 0 and 1).

What confused me is that in Merlin, they applied the same kind of transformation on `ap` as `sp` when preparing the features:

> 
```
### convert sp to mgc ###
$sptk/x2x +df ${sp_dir}/$file_id.sp | $sptk/sopr -R -m 32768.0 | $sptk/mcep -a $alpha -m $mcsize -l $nFFTHalf -e 1.0E-8 -j 0 -f 0.0 -q 3 > ${mgc_dir}/$file_id.mgc

### convert ap to bap ###
$sptk/x2x +df ${bap_dir}/$file_id.ap | $sptk/sopr -R -m 32768.0 | $sptk/mcep -a $alpha -m $order -l $nFFTHalf -e 1.0E-8 -j 0 -f 0.0 -q 3 > ${bap_dir}/$file_id.bap
```

As far as I know, `ap` of WORLD is quite different from that of STRAIGHT? While this kind of transformation is applicable to STRAIGHT's `ap`.

**Comment by mmorise** [comment]
As you mentioned, `ap` of WORLD uses a different representation compared with that of STRAIGHT.
Perhaps, STRAIGHT uses logarithmic representation of aperiodicity of WORLD.
The unit of `ap` of STRAIGHT maybe dB (which means 20 (or 10?) * log10('ap' of WORLD) is 'ap' of STRAIGHT).

Unfortunately, I don't have enough knowledge in the Merlin toolkit.
I think that we can avoid the illogical waveform by setting a safe guard in the synthesis function.
