### ISSUE TITLE
Are there any resources I could use to learn how to manipulate the spectrogram output of world ?

### ISSUE THREAD

**Issue by SeleDreams** [mmorise/World#140]
Hi, I'm sorry to bother you.
I am working on programming a software based on world and I would like to modify the output spectrogram analyzed by world before synthesizing it, however I am not sure about the best way to go about it
are there resources that could help to learn ?

**Comment by mmorise** [comment]
It is difficult to comment because your purpose is unclear.
Since there are different approaches, I recommend you investigate the paper on voice conversion research.
