### ISSUE TITLE
Errors setting fft_plan components.

### ISSUE THREAD

**Issue by pacomacman** [mmorise/World#144]
In FFT.c there are two functions BackwardFFT and ForwardFFT that take one parameter fft_plan p.

Anywhere these functions access or try and set values in the plan I'm seeing a compiler error.

static void BackwardFFT(fft_plan p) {
    if (p.c_out == NULL) {  // Error: Incomplete definition of type 'fftw_plan_s'
   }
}

So anywhere in your code where you use or create an empty plan and attempt to access components of that plan it seems are not compatible with my compiler (XCode compiling to iOS).

It is suggesting:
Member reference type 'fftw_plan' (aka 'fftw_plan_s *') is a pointer; did you mean to use '->'?

But obviously that doesn't work. Has anyone ported the WORLD code over to iOS do you know or have you any idea why this is happening?

**Comment by mmorise** [comment]
Could you please check for errors using test.c? We have confirmed that it works on iOS. Users do not need to touch FFT directly.
