### ISSUE TITLE
F0 contour of C version is different from that of matlab version

### ISSUE THREAD

**Issue by tuanad121** [mmorise/World#17]
![figure_1](https://cloud.githubusercontent.com/assets/4689794/21416005/0c97fd58-c7c4-11e6-98b9-9b4d91877fb7.png)
I compare C version and Matlab version of World vocoder by analyzing a waveform. I see difference in F0 between the 2 versions (at frame 170 and frame 700). They're supposed to be the same. So I wonder what's going on. :)

This is my [test file](https://drive.google.com/open?id=0ByWazFhIkXGabzhGSkNpVDJSTHc)

**Comment by mmorise** [comment]
Thank you for your report.
I'll check the source code with your test file.
Please give me a time for verification.

**Comment by mmorise** [comment]
Sorry, I can't recreate your result.
If possible, please give me the information (e.g. command used in MATLAB, version of it and OS).
Default analysis command
> r = Harvest(x, fs);
was not able to recreate your figure.

On the other hand, I found a bug when using "Debug x86" in Visual Studio.
In any case, I think that a debug is required.

**Comment by tuanad121** [comment]
Thanks for your replies. I use Octave 4.0.3 instead of Matlab. I use MacOS 10.12.1. 
I use testWorld.m and default setting to run the program. Is your Matlab code result the same as C program.
Thanks for spending your time on my issue.
