### ISSUE TITLE
D4C threshold option

### ISSUE THREAD

**Issue by wuaalb** [mmorise/World#21]
I was using an older version of WORLD with good results, but after updating some voiced frames are estimated to have an aperiodicity of 1.0 (and thus in synthesis they sound unvoiced).

![image](https://cloud.githubusercontent.com/assets/8669162/23472775/3fc78970-feae-11e6-8b24-828c6362dfda.png)

If I set the D4C `threshold` option to 0.0, this issue is avoided, but I have no idea what this parameter is supposed to do or how to set it.

From the code I understand that if the D4C "Love Train" (?) estimate is below this threshold, aperodicity 1.0 is used (same as for unvoiced frames); but I'm not sure what problem this is trying to fix.

Could you please clarify this a bit?

**Comment by mmorise** [comment]
You can control this threshold by using the struct D4COption.
Please see the 204th line in test.cpp, 
  option.threshold = 0.85;
You can modify the threshold used for D4C LoveTrain.
In cases where you set the threshold to 0.0, D4C() work as the conventional version as you pointed out.

This function was implemented for Harvest F0 estimator.
Harvest is designed to reduce the error that the voiced section is wrongly identified as the unvoiced section.
The fricative therefore tends to be counted as the voiced section in cases where Harvest is used.
D4C LoveTrain extracts the fricative identified as the voiced section and give it the 1.0 of aperiodicity.
(The value 1.0 means that the excitation signal in synthesis() is the white noise.)

If my point is different from your issue, please ask me with another question.

**Comment by wuaalb** [comment]
Great, thank you. That's exactly what I wanted to know.
