### ISSUE TITLE
DIO/Stonemask vs. Harvest

### ISSUE THREAD

**Issue by m-toman** [mmorise/World#35]
Hi,

I've been testing the latest version of WORLD via the codec_test example (b) and compared it with the analysis_synthesis (a) example.

I found that (b) does not produce unvoiced sections for my samples (except for the silence in the beginning) while (a) does. Interestingly, the resynthesis is fine - but training a synthesizer on those obviously results in fully voiced sentences.

Here is an example input wav:
https://drive.google.com/open?id=0B2D9egvk27W3c2x0QnVYRnVwLWs

Then the f0 trajectory generated by (a):
https://drive.google.com/open?id=0B2D9egvk27W3OHNBaFhsQmhNYW8
Produced by:
```
./analysis input.wav a.f0 a.sp a.ap
x2x +da a.f0 > a.f0.ascii
```

and by (b):
https://drive.google.com/open?id=0B2D9egvk27W3dElSMTBFRWlGS1U
please note that I didn't prune the header here, so the first 3 lines can be ignored.
Produced by:
```
./f0analysis input.wav -o b.f0
x2x +da b.f0 > b.f0.ascii
```

So I'm missing the unvoiced sections in (b), or am I missing something here?

Thanks!
Markus

**Comment by mmorise** [comment]
Thank you for your question.

As you mentioned, (b) does not contain the unvoiced section.
Harvest was designed to reduce the error that the voiced section is wrongly identified as the unvoiced section.
Even if the F0 is given in unvoiced section, we can maintain the good result by the aperiodicity.
D4C has a function to identify the frame whether it is voiced or unvoiced.
We will obtain 1.0 (there is no periodic component) as the aperiodicity when it identified the frame as unvoiced section.
So we can obtain the unvoiced waveform from voiced frame having an F0, provided that D4C identified the frame as unvoiced section.

Since the continuous F0 modeling achieves the good result in statistical parametric speech synthesis, I developed Harvest to assist it.

Best regards,

**Comment by m-toman** [comment]
Thank you, that means I can get the VUV information from the aperiodicity features and instead of interpolating F0 over unvoiced frames, I can use the values from WORLD. 

For synthesis I could then either predict the VUV values directly or again get it from the predicted aperiodicity features?

**Comment by mmorise** [comment]
Yes, you can obtain the VUV information from the aperiodicity.
Aperiodicity has the time-frequency representation, and the value at 0 Hz depends on the VUV information.
If the aperiodicity at 0 Hz is above 0.5, the frame is the unvoiced section.

To be precise, the aperiodicity at 0 Hz is near 1.0 (0 dB) in unvoiced frame.
Else, it is 0.001 (-60 dB).

**Comment by m-toman** [comment]
Thanks. Actually, when thinking about it, it should therefore work without explicit VUV information, as the resynthesis (codec_test/readandsynthesis) example doesn't need it either.

What I am currently using for feature extraction is:
```
    $world/build/f0analysis ${wav_dir}/$file_id.wav -o ${f0_dir}/$file_id.f0_d_header
    $world/build/spanalysis ${wav_dir}/$file_id.wav ${f0_dir}/$file_id.f0_d_header -d 60 -o ${mgc_dir}/$file_id.mgc_d_header
    $world/build/apanalysis ${wav_dir}/$file_id.wav ${f0_dir}/$file_id.f0_d_header -f $nFFTHalf -c -o ${bap_dir}/$file_id.bap_d_header
 
    # remove header from spectrum and convert to float
    # SP header length is 48
    tail -c +49 ${mgc_dir}/$file_id.mgc_d_header | $sptk/x2x +df > ${mgc_dir}/$file_id.mgc

    # remove header from F0, convert to float and to LF0
    # F0 header length is 24
    tail -c +25 ${f0_dir}/$file_id.f0_d_header | $sptk/x2x +df | $sptk/sopr -magic 0.0 -LN -MAGIC -1.0E+10 > ${lf0_dir}/$file_id.lf0

    # remove header from bap, convert to float
    # AP header length is 48
    tail -c +49 ${bap_dir}/$file_id.bap_d_header | $sptk/x2x +df > ${bap_dir}/$file_id.bap
```
So I'm pruning the headers so I can use the features as input to the model training.

And then at synthesis time:
```
sopr -magic -1.0E+10 -EXP -MAGIC 0.0 $lf0 | x2x +fd > ${output}.f0
sopr -c 0 $ap | x2x +fd > ${output}.ap
x2x +fd $sp > ${output}.sp

$synthraw ${output}.f0 ${output}.sp ${output}.ap -o ${output}.wav
```
Where synthraw is derived from readandsynthesis but operates without headers.

Running those on a waveform works well.
But when feeding it to the synthesis training I end up with something like:
https://drive.google.com/open?id=0B7CaBZQJOworQ1BDM1BxVERoWm8

If you have an idea what could cause this, I'd be glad. Otherwise thanks for the information and I'll close the issue :)

**Comment by mmorise** [comment]
Sorry, it is difficult for me to identify the cause of this problem.
Followings are my impressions with no evidence.
(1) In the second example, I feel that the voiced sections were reproduced as the sound with APs above 1.0.
(2) There is a white noise in almost whole sections. This suggests that the generated spectral envelope is inappropriate. In the silent section, the spectral envelope should have a low power.

The generated speech parameters seem to contain unwanted parameters.
You may see the cause by displaying the generated parameters.

**Comment by m-toman** [comment]
Sorry for the late reply. Thank you, I think I finally figured everything out. It seems to work pretty well without explicitly modeling VUV.
The problem here were just a few messed up dimensions.
