### ISSUE TITLE
optimization for android platform?

### ISSUE THREAD

**Issue by attitudechunfeng** [mmorise/World#55]
I'd like to know is there an optimization version of world for mobile platform such as android?

**Comment by mmorise** [comment]
Sorry, what is the optimization in this case?
Since WORLD is implemented in C++ that does not include OS-dependent code, you are able to use it in any platform that can compile C++.
If possible, please give me more information in the optimization.

**Comment by attitudechunfeng** [comment]
I have  attempted to make WORLD run on android platform, and in fact it can work well. However, when synthesize audio, its speed is 10 times slower than it performances on PC. So my question is that is there any android(arm) platform specified optimization to narrow the speed gap of different platforms?

**Comment by mmorise** [comment]
Unfortunately, I don't have any optimized version for android platform.
It is difficult for the current algorithm to achieve the required speed.
Down sampling is one of the ideas, but it would not be able to achieve the requirement.

I'm trying to speed up it, and the prototype can achieve the speed that is two times faster than the current version.

**Comment by attitudechunfeng** [comment]
Could you provide the prototype version of codes? thks

**Comment by mmorise** [comment]
It is not implemented on C++ (I usually use MATLAB for test).
I'll released the alpha version after implementing on C++.
There are several bugs in this version, so I'm debugging.

**Comment by attitudechunfeng** [comment]
I'm looking forward it!

**Comment by bfs18** [comment]
Hi @mmorise any update?

**Comment by attitudechunfeng** [comment]
邮件已收~谢谢 by 王春峰
