### ISSUE TITLE
Maybe There is one thing wrong in the source file <harvest.cpp>

### ISSUE THREAD

**Issue by jiqizaisikao** [mmorise/World#58]
the function void Harvest::GetSpectra(...)
 main_spectrum[i][1] = -forward_real_fft->spectrum[i][1]
it seems that the wright one is:
 main_spectrum[i][1] = forward_real_fft->spectrum[i][1]
It is a small mistake that will not cause a lot of pitch errors,but If you tried the other Harvest matlab source code ,than you will find their results are different(It seems that their algorithms are all the same)。The pitches obtained by matlab version are more smooth and have little jumping pitch points.Your programe gets some errs  sometimes.
After I fixed it,their resluts are neally the same,so maybe it is wrong,and I checked my fftw(I replaced the fft lib with fftw,but  the fftw output are the same with your fft lib),so there is no need to add a minus sign.

**Comment by jiqizaisikao** [comment]
For  this reason ,The instantant frequency obtainted are wrong,but harverst uses the instantant frequency heavily,so the out pitches are wrong sometimes.

**Comment by mmorise** [comment]
Thank you for your comment.
Since I don't have enough time to check it during this week, please wait for a while.

The main problem of confusion is the FFT library I used.
The sign of the imaginary part is reversed compared with MATLAB version.
I may mistake the modification of the equation for calculating the instantaneous frequency.

**Comment by mmorise** [comment]
I uploaded the new version.
I think that you will be able to use FFTW without the particular modification for WORLD.

**Comment by jiqizaisikao** [comment]
but，i test fftw and your fft function are the same,they out put the same,maye i was wrong
