### ISSUE TITLE
Segmentation fault in Dio

### ISSUE THREAD

**Issue by takenori-y** [mmorise/World#62]
If a very short waveform is given to Dio(), a segmentation fault is caused. The minimum length of waveform causes the segmentation fault seems to depend on sampling rate and floor F0.

**Comment by mmorise** [comment]
There are several causes in the segmentation fault.
In cases where the signal's amplitudes in all frames are completely zero, the Dio() would not be able to work.
Adding a low-SNR noise is effective to avoid this error.
If you have a waveform that causes a segmentation fault, please give me the file if possible.
I will check the source code by using the file and fix the bug.

**Comment by takenori-y** [comment]
Thank you for your quick reply.
I attached the waveform that causes a segmentation fault. When the floor F0 is 60 Hz and the sampling frequency is 16 kHz, the waveform whose length is less than 480 causes the problem.
[tmp.zip](https://github.com/mmorise/World/files/1793496/tmp.zip)

**Comment by mmorise** [comment]
Thank you very much.
I will check the source code this weekend.
(If I find a serious bug, please give me more days.
I have no time next week because of a business trip.)

**Comment by mmorise** [comment]
I updated the source code.
StoneMask() was also modified because it cause another error.

**Comment by takenori-y** [comment]
Thank you for your quick response.
I used the latest source code, but a waveform whose length is between 80 and 130 still caused a segmentation fault. I attached it.
[tmp2.zip](https://github.com/mmorise/World/files/1797153/tmp2.zip)

**Comment by mmorise** [comment]
Sorry, I cannot confirm the error in Dio(), but Harvest() caused a segmentation fault.
If Dio() cannot work as you pointed out, please give me more information.
I will check the source code in Harvest().

**Comment by mmorise** [comment]
I fixed a bug in Harvest().
I think that the limitation in the length was removed.

**Comment by takenori-y** [comment]
I modified dio.cpp in the same way as harvest.cpp. The problem is solved. Thank you!
