### ISSUE TITLE
 If it's possible to speed up WORLD by using FFTW

### ISSUE THREAD

**Issue by candlewill** [mmorise/World#68]
I am wondering if it's possible to speed up WORLD by using FFTW as the fft backend instead. Has someone do the experiments? If it is possible, could someone tell me how to do the replace.

**Comment by candlewill** [comment]
Problem resolved.

**Comment by hdmjdp** [comment]
Hi, Do you have a fast method fo speed up world?

**Comment by mmorise** [comment]
In CheapTrick and D4C, It would be possible to speed up the world by using parallel GPU computing.
Since the FFT is the most massive computation, using another FFT library may be useful for speed up.

**Comment by hdmjdp** [comment]
@thanks，we have using a fast fft library, and we use the world on devices which has not gpu.
