### ISSUE TITLE
Why the value of `sp` is so large

### ISSUE THREAD

**Issue by candlewill** [mmorise/World#70]
I try to extract acoustic parameters using the tool `examples/analysis_synthesis/analysis`. I can get the three parameters. But when I check the values of the `sp` file. I found that `abs` of some value is very very large, for example, `-1.59584e+165`, `7.15049e+43`. 

```shell
analysis 000001.wav 000001.f0 000001.sp 000001.ap
```

The way I used to get the value of `sp` file is: `x2x +da 000001.sp`.  `x2x` bin is from the latest `SPTK` tool.

Could anyone help explain if there is something wrong?

The wave to analysis is attached.
[000001.zip](https://github.com/mmorise/World/files/2378095/000001.zip)

**Comment by mmorise** [comment]
The header of the attached file shows that it is not a linear PCM.
File loader in WORLD supports only the simple linear PCM.

http://soundfile.sapp.org/doc/WaveFormat/
Subchunk1Size is generally 16 for PCM, but the attached file's size is not 16.
By modifying the header, I could read and analyze the file.
The result did not include such large values.

**Comment by candlewill** [comment]
Thanks @mmorise . That solved my problem.

**Comment by songmeixu** [comment]
> The header of the attached file shows that it is not a linear PCM.
> File loader in WORLD supports only the simple linear PCM.
> 
> http://soundfile.sapp.org/doc/WaveFormat/
> Subchunk1Size is generally 16 for PCM, but the attached file's size is not 16.
> By modifying the header, I could read and analyze the file.
> The result did not include such large values.

Hello @mmorise ! I checked the `Subchunk1Size` of wav that @candlewill supplied, it is `16`. 
![image](https://user-images.githubusercontent.com/705582/51673329-b4ffc900-2008-11e9-905d-dfd683e3ff95.png)

Could you check this wav again or describe how you modified the header?

**Comment by mmorise** [comment]
I checked the file and confirmed that it was not the same as the old one.
The URL to download the file seems to be changed.

Old: https://github.com/mmorise/World/files/2378030/000001.zip
New: https://github.com/mmorise/World/files/2378095/000001.zip

So, you would be able to load new file by using the loader in WORLD.

**Comment by songmeixu** [comment]
I see. thank you！👍🏻

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: mmorise <notifications@github.com>
发送时间: Thursday, January 24, 2019 8:54:38 PM
收件人: mmorise/World
抄送: Meixu Song; Comment
主题: Re: [mmorise/World] Why the value of `sp` is so large (#70)


I checked the file and confirmed that it was not the same as the old one.
The URL to download the file seems to be changed.

Old: https://github.com/mmorise/World/files/2378030/000001.zip
New: https://github.com/mmorise/World/files/2378095/000001.zip

So, you would be able to load new file by using the loader in WORLD.

**Comment by candlewill** [comment]
Thanks @mmorise . I downloaded the wav from the [new 2378095/000001.zip](https://github.com/mmorise/World/files/2378095/000001.zip). The `sp` parameters still contains some big values:
command:
```shell
./build/analysis 000001.wav  f0 sp ap
x2x +da sp | head
```
result:
```
7.90505e-320
-3.80046e-118
-1.10136e+190
-2.02275e-201
-1.60101e-49
-1.61272e-295
1.29486e-216
5.34522e+78
5.95244e+26
58.0803

```

**Comment by mmorise** [comment]
I tested the file by using an example in example/parameter_io.

```
./build/f0analysis.exe 000001.wav
./build/spanalysis.exe 000001.wav output.f0
```
You can obtain output.sp as the parameter in spectral envelope.

As a result, such big values was not contained in the file.
I think that the example contains a bug.

Since I'm not the developer in the example, I can't support to debug it.
I recommend you to use the example in parameter_io.

**Comment by candlewill** [comment]
Thanks, I would try it.
