### ISSUE TITLE
minor bug in synthesisrealtime.cpp?

### ISSUE THREAD

**Issue by pallashadow** [mmorise/World#73]
Calling Synthesis2 function with lower fft_size (fft_size=256 on sample_rate=24000) would cause some minor "bip" noise. Which would not occur when calling Synthesis function. 

I fixed this noise by editting the line 590 in src/synthesisrealtime.cpp to be identical with src/synthesis.cpp
`
//index = MyMaxInt(0, i + offset - synth->fft_size / 2 + 1);
index = i + offset - synth->fft_size / 2 + 1;
if (index <0) continue; 
`

is this solution reasonable? Thanks for your help

**Comment by mmorise** [comment]
Sorry, I'm busy until this weekend due to other tasks.
I will be able to check it in next week.

**Comment by mmorise** [comment]
I reflected your comment.
Thank you again for your nice comment.

**Comment by pallashadow** [comment]
Your work is really fantastic for industrial applications, and helped many people. You'd be surprised at how little praise people receive for doing something great. 
Thank you very much, sincerely.
