### ISSUE TITLE
PLATINUM and D4C

### ISSUE THREAD

**Issue by GloomyGhost-MosquitoCoil** [mmorise/World#80]
What is the function of PLATINUM's pt100 function in the new version? how to use? The pCount in the old version corresponds to what is in the new version.

**Comment by mmorise** [comment]
The function pt100 is implemented for UTAU that is a singing synthesizer.
I don't recommend to use this function for general speech analysis/synthesis.
(I would not able to maintain it because I have forgotten it...)

**Comment by GloomyGhost-MosquitoCoil** [comment]
Yes, I'm using it for singing synthesis.
I will rewrite it,Thanks!

**Comment by GloomyGhost-MosquitoCoil** [comment]
Also, is there a similar function in the new version of word?

**Comment by mmorise** [comment]
No, I don't implement such function because D4C edition uses another representation for the aperiodic parameter. Official project don't provide it, but it would be possible to implement a function for singing synthesizer.

**Comment by GloomyGhost-MosquitoCoil** [comment]
Thanks
