### ISSUE TITLE
Missing codec.cc in makefile

### ISSUE THREAD

**Issue by takenori-y** [mmorise/World#93]
`codec.cc` is not described in `makefile` nor `win.vcxproj`. Is there any reason for that? The functions in `codec.cc` seems to be beneficial for processing aperiodicity.

**Comment by mmorise** [comment]
The main reason is that the codec is not necessary for simple speech analysis/synthesis processing. There is an example in "examples/codec_test."

**Comment by takenori-y** [comment]
I see. Thank you for answering.
