### ISSUE TITLE
fftlen=512 will introduce noise (burrs)

### ISSUE THREAD

**Issue by hdmjdp** [mmorise/World#98]
![图片](https://user-images.githubusercontent.com/26831425/83838876-0bb50100-a72d-11ea-9ae8-db17c152a264.png)
![图片](https://user-images.githubusercontent.com/26831425/83838884-11aae200-a72d-11ea-875b-73ef1722f964.png)

**Comment by hdmjdp** [comment]
@mmorise hi, dou you know what cause this?

**Comment by mmorise** [comment]
Since there are too many possibilities, I cannot answer the question from only provided figures. Please give me detailed information and explanation, including waveform and source code.

**Comment by hdmjdp** [comment]
> Since there are too many possibilities, I cannot answer the question from only provided figures. Please give me detailed information and explanation, including waveform and source code.
I get the acoustic features(sp, bap, f0) using analysis code with fft_len=512. And then I just use these features to synthesis the wav below.

[512.wav.zip](https://github.com/mmorise/World/files/4781606/512.wav.zip)

**Comment by mmorise** [comment]
Thank you for your information.

The cause is the lack of signal length in low-F0 frames. For example, D4C requires a length of 4*T0. In cases where the F0 at a frame is 100 Hz, D4C uses the frame length of 40 ms. The sampling frequency of 512.wav was 24,000 Hz. The frame length of 40 ms is 960 samples, so the fft_size of 512 cannot cover this frame length. When the fft_size is 512, you can use the F0 around 188 Hz as the lower limit.

**Comment by hdmjdp** [comment]
@mmorise Thank you, I will try.

**Comment by hdmjdp** [comment]
@mmorise But，if i use f0_ceil=188, the synthesis wav will be dummy as below. how to solvle this.
[188.wav.zip](https://github.com/mmorise/World/files/4787661/188.wav.zip)

**Comment by mmorise** [comment]
Sorry, 188 Hz is the lower limit that you can analyze/synthesize the speech when you use the fft_size of 512 samples. In other words, you can process speech with the F0s at least above 188 Hz in all frames. Unfortunately, the F0s of your sample contained frames with the F0 below 188 Hz, so you cannot analyze/synthesize it by using the fft_size of 512 samples.
