### ISSUE TITLE
Positions of Frame Centers

### ISSUE THREAD

**Issue by Novak3** [mmorise/World#99]
I understand from [Issue #51](https://github.com/mmorise/World/issues/51) that we cannot specify or control the length of the frames, and that these are controlled by the F0 input from the DIO algorithm.  

I'm a little confused by the notion of having a different frame length (or perhaps more precisely, window length) for both CheapTrick (3T) and D4C (4T).  Is it possible to determine the sample which corresponds to the center of an arbitrary frame generated by World, and if so, how?

**Comment by mmorise** [comment]
CheapTrick and D4C use the same temporal position for the processing. In cases where the temporal position is $t$, their analysis ranges are $t \pm 1.5*T_0$ and $t \pm 2*T_0$, respectively. So, the center of an arbitrary frame is the same in both algorithms.

**Comment by Novak3** [comment]
So if the sampling rate is 16 KHz, the frame advance is 5 ms, then the frame centers are at sample 0, 80, 160, etc? 

I took a look at a python implementation, and that was the implication I got.

**Comment by mmorise** [comment]
Yes, the center is determined as you pointed out. You obtain the frame length from the fundamental period (T0) automatically.

**Comment by Novak3** [comment]
Excellent, thanks.
